-- Run once in Supabase SQL Editor
create table if not exists public.portfolio_media (
  id bigint generated by default as identity primary key,
  file_path text not null unique,
  public_url text not null,
  media_type text not null check (media_type in ('image','video')),
  title text not null,
  caption text,
  category text,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.portfolio_media enable row level security;

-- No browser client writes are used. ASP.NET Core uses the server-side secret key.
-- Public gallery reads also go through ASP.NET Core, so no public table policy is required.

-- Create a PUBLIC storage bucket named: portfolio
-- Dashboard: Storage -> New bucket -> portfolio -> Public bucket
